import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  wiki: [
    {
      type: 'autogenerated',
      dirName: 'music-publishing'
    },
  ],
  tulbox: [
    {
      type: 'autogenerated',
      dirName: 'tulbox'
    },
  ],
};

export default sidebars;
